DROP DATABASE IF EXISTS LIBRARY;

CREATE DATABASE LIBRARY;

USE LIBRARY;

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
Isbn BIGINT,
Title VARCHAR(210),
PRIMARY KEY(Isbn));

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
Author_id INT AUTO_INCREMENT,
Name VARCHAR(100),
PRIMARY KEY(Author_id));

DROP TABLE IF EXISTS BOOK_AUTHORS;
CREATE TABLE BOOK_AUTHORS(
Author_id INT,
Isbn BIGINT,
PRIMARY KEY(Author_id,Isbn),
FOREIGN KEY(Author_id) REFERENCES AUTHORS(Author_id),
FOREIGN KEY(Isbn) REFERENCES BOOK(Isbn));

DROP TABLE IF EXISTS BORROWER;
CREATE TABLE BORROWER(
Card_id INT AUTO_INCREMENT,
Ssn CHAR(11) NOT NULL,
Bname VARCHAR(30) NOT NULL,
Address VARCHAR(200) NOT NULL,
Phone VARCHAR(30) NOT NULL,
PRIMARY KEY(Card_id),
UNIQUE(Ssn));

DROP TABLE IF EXISTS BOOK_LOANS;
CREATE TABLE BOOK_LOANS(
Loan_id INT AUTO_INCREMENT,
Isbn BIGINT,
Card_id INT,
Date_out DATE,
Due_date DATE,
Date_in DATE,
PRIMARY KEY(Loan_id),
FOREIGN KEY(Isbn) REFERENCES BOOK(Isbn),
FOREIGN KEY(Card_id) REFERENCES BORROWER(Card_id));

DROP TABLE IF EXISTS FINES;
CREATE TABLE FINES(
Loan_id INT,
Fine_amt FLOAT DEFAULT 0,
Paid BOOLEAN DEFAULT False,
PRIMARY KEY(Loan_id),
FOREIGN KEY(Loan_id) REFERENCES BOOK_LOANS(Loan_id));

DROP TABLE IF EXISTS LIBRARIANS;
CREATE TABLE LIBRARIANS(
Empid INT,
Password VARCHAR(30),
UNIQUE(Empid),
UNIQUE(Password));

LOAD DATA LOCAL INFILE 
'/Users/mohammedkhaja/Downloads/KMM190000_cs6360/book_table.csv' INTO TABLE BOOK FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'(Isbn,Title);

LOAD DATA LOCAL INFILE 
'/Users/mohammedkhaja/Downloads/KMM190000_cs6360/author_table.csv' INTO TABLE AUTHORS FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'(Author_id,Name);

LOAD DATA LOCAL INFILE 
'/Users/mohammedkhaja/Downloads/KMM190000_cs6360/book_author_table.csv' INTO TABLE BOOK_AUTHORS FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'(Author_id,Isbn);

LOAD DATA LOCAL INFILE 
'/Users/mohammedkhaja/Downloads/KMM190000_cs6360/borrower_table.csv' INTO TABLE BORROWER FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n'(Card_id,ssn,Bname,Address,Phone);

 

